- name: Website
  hosts: all
  tasks:
    - name: Create directory structure
      win_file:
       path: C:\sites\acme
       state: directory
    - name: Acme IIS site
      win_iis_website:
        name: "Acme"
        state: started
        port: 80
        ip: 127.0.0.1
        physical_path: C:\sites\acme
      register: website
